name: Reporte validación estado flota

on:
  workflow_dispatch:

jobs:
  generar-y-enviar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar librerías
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas openpyxl

      - name: Generar reporte y enviar correo
        env:
          DRIVIN_API_KEY: ${{ secrets.DRIVIN_API_KEY }}
          CORREO_ORIGEN: ${{ secrets.EMAIL_USER }}
          CORREO_DESTINO: ${{ secrets.EMAIL_TO }}
          GMAIL_APP_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

        run: python eventos_mal_clasificados_correo.py
